name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git openjdk-17-jdk python3-pip unzip wget
          pip install buildozer cython

      - name: Install Android SDK
        run: |
          sudo mkdir -p /usr/lib/android-sdk/cmdline-tools
          cd /usr/lib/android-sdk/cmdline-tools
          sudo wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          sudo unzip cmdline-tools.zip
          sudo mv cmdline-tools latest
          export ANDROID_HOME=/usr/lib/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk
